---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/events":
    get:
      summary: Retrieves all events
      tags:
      - Events
      responses:
        '200':
          description: events found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    date:
                      type: string
                      format: date_time
                    location:
                      type: string
                    total_seats:
                      type: integer
                    created_at:
                      type: string
                      format: date_time
                    updated_at:
                      type: string
                      format: date_time
                  required:
                  - id
                  - name
                  - date
                  - location
                  - total_seats
    post:
      summary: Creates an event
      tags:
      - Events
      parameters: []
      responses:
        '201':
          description: event created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date:
                  type: string
                  format: date_time
                location:
                  type: string
                total_seats:
                  type: integer
              required:
              - name
              - date
              - location
              - total_seats
  "/events/{id}":
    get:
      summary: Retrieves an event
      tags:
      - Events
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: event found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  date:
                    type: string
                    format: date_time
                  location:
                    type: string
                  total_seats:
                    type: integer
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - name
                - date
                - location
                - total_seats
        '404':
          description: event not found
    patch:
      summary: Updates an event
      tags:
      - Events
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: event updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date:
                  type: string
                  format: date_time
                location:
                  type: string
                total_seats:
                  type: integer
    delete:
      summary: Deletes an event
      tags:
      - Events
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: event deleted
  "/seats":
    get:
      summary: Retrieves all seats
      tags:
      - Seats
      responses:
        '200':
          description: seats found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    event_id:
                      type: integer
                    name:
                      type: string
                    status:
                      type: string
                    price:
                      type: number
                    created_at:
                      type: string
                      format: date_time
                    updated_at:
                      type: string
                      format: date_time
                  required:
                  - id
                  - event_id
                  - name
                  - status
                  - price
    post:
      summary: Creates a seat
      tags:
      - Seats
      parameters: []
      responses:
        '201':
          description: seat created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                name:
                  type: string
                status:
                  type: string
                price:
                  type: number
              required:
              - event_id
              - name
              - status
              - price
  "/seats/{id}":
    get:
      summary: Retrieves a seat
      tags:
      - Seats
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: seat found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  event_id:
                    type: integer
                  name:
                    type: string
                  status:
                    type: string
                  price:
                    type: number
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - event_id
                - name
                - status
                - price
        '404':
          description: seat not found
    patch:
      summary: Updates a seat
      tags:
      - Seats
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: seat updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                name:
                  type: string
                status:
                  type: string
                price:
                  type: number
    delete:
      summary: Deletes a seat
      tags:
      - Seats
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: seat deleted
  "/tickets":
    post:
      summary: Creates a ticket
      tags:
      - Tickets
      parameters: []
      responses:
        '201':
          description: ticket created
        '422':
          description: unprocessable entity
        '404':
          description: seat not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                seat_id:
                  type: integer
                user_email:
                  type: string
              required:
              - seat_id
              - user_email
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
